### ISSUE TITLE
Recommend a linter for Swift?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xswift#10]
This may or may not be appropriate in this language. See exercism/docs#54 for details.

**Comment by masters3d** [comment]
There is an experimental one

**Comment by masters3d** [comment]
We probably wont have a real linter for some time.

**Comment by yurrriq** [comment]
:+1: for SwiftLint!

**Comment by jonallured** [comment]
I've been using SwiftLint on a production project and we've really liked it. Also, houndci.com supports Swift. What's important to me is having some sort of consistency, which ruleset is used less so.

What can I do to move this forward?

**Comment by masters3d** [comment]
hound looks interesting. https://houndci.com/configuration#swift 
@kytrinyx what do you think?

**Comment by masters3d** [comment]
This would be something that would fit perfectly when we move to swift 3 in a couple of months.

**Comment by kytrinyx** [comment]
I haven't written any swift, so I don't have a basis for comparison.

@marianaIAm have you by any chance written enough Swift in production to have experiential knowledge of linters and style rules?

**Comment by yurrriq** [comment]
It looks like Hound CI wraps SwiftLint. I've found SwiftLint to be great over the last n months and would definitely recommend it. Perhaps the real question is: what's a good config to recommend?

**Comment by masters3d** [comment]
I think the default rules are fine except for these:
```
disabled_rules: # rule identifiers to exclude from running
  - force_try
  - function_body_length
  - line_length
  - variable_name
```

The reason is that some of the tests have really long lines while others use force try to keep the code simple for the tests. Variable names rule is really opinionated as it won't even allow short variables like `i`

I am going to turn on the swiftlinter as part of Travis when we update to swift 3.0
https://github.com/exercism/xswift/pull/155

**Comment by jonallured** [comment]
@masters3d agreed!

The only quibble I'd have is the variable names one: I think short var names are an anti-pattern, but make not worth having the linter complain?

**Comment by masters3d** [comment]
I guess instead of disabling `variable_name` we could downgrade it to a warning instead of an error. 

```
variable_name: 
    min_length: 
        warning: 1
        error: 0

force_try: warning
    
disabled_rules: # rule identifiers to exclude from running
  - function_body_length
  - line_length
```

**Comment by masters3d** [comment]
We are adopting SwiftLint for swift3.
