### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xswift#104]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by masters3d** [comment]
We are good here

``` swift
    func testTrianglesViolatingTriangleInequalityAreIllegal2() {
        XCTAssertEqual(triangleKind.ErrorKind,  Triangle(2, 4, 2).kind)
    }

```

**Comment by kytrinyx** [comment]
No, it shouldn't be illegal, it should be isosceles, right?

>  the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side - https://en.wikipedia.org/wiki/Triangle_inequality

**Comment by masters3d** [comment]
ha, yeah. I should know this from playing with my kid this game. 
http://dragonbox.com/elements
![image](https://cloud.githubusercontent.com/assets/6539412/12691611/5c39e584-c6a2-11e5-8aa8-7d79c827ca79.png)

**Comment by kytrinyx** [comment]
:) I hear wonderful things about that game.

**Comment by hankturowski** [comment]
Sorry I'm late to the party.

The .md currently says that the length of two sides must always *exceed* the third. The degenerate triangle (where a+b=c) is a strange case and we should probably call it out directly as being a valid case.

From the problem definition:

> The sum of the lengths of any two sides of a triangle always exceeds the length of the third side, a principle known as the triangle inequality.

**Comment by masters3d** [comment]
https://github.com/exercism/xerlang/issues/85#issuecomment-177077011

**Comment by masters3d** [comment]
https://github.com/exercism/xswift/pull/106
