### ISSUE TITLE
Improve 'Setup' documentation

### ISSUE THREAD

**Issue by embryoconcepts** [exercism/xswift#119]
The documentation to begin working through the Swift exercises could use some clarification. It's a multi-step process to integrate the test file with a new project, solve the exercise, and submit correctly.

1. Create a new project with Xcode, in the same folder as the Exercism test file:
![screen shot 2016-02-29 at 1 50 17 pm](https://cloud.githubusercontent.com/assets/1554169/13405215/67123310-deeb-11e5-9a2e-7c375ee5fad6.png)

2. Drag the Exercism test file into the <project_name>Tests group, and add the line `@testable import <project_name> ` on the second line of the Exercism test file:
![screen shot 2016-02-29 at 1 50 48 pm](https://cloud.githubusercontent.com/assets/1554169/13405240/7f1aadfc-deeb-11e5-8aa5-3ca7e1a12312.png)

3. Create the working file/class, and save **in the same folder as the Exercism test file**: _[see first image]_

4. When you are ready to submit, do so from the folder that contains the working file and the Exercism test file

**Comment by masters3d** [comment]
Nice suggestions!
Do you mind summiting an update PR to this doc ? https://github.com/exercism/xswift/blob/master/docs/TESTS.md

**Comment by embryoconcepts** [comment]
@masters3d All set! https://github.com/exercism/xswift/pull/120

**Comment by masters3d** [comment]
Looks good! thanks
