### ISSUE TITLE
binary: improve tests for invalid numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xswift#135]
We should have separate tests for:

- alphabetic characters at the beginning of a valid binary number
- alphabetic characters at the end of a valid binary number
- alphabetic characters in the middle of an otherwise valid binary number
- invalid digits (e.g. 2)

If the test suite for binary has test cases that cover these edge cases, this issue can safely be closed.

See https://github.com/exercism/x-common/issues/95

**Comment by masters3d** [comment]
Some of this was done here:
https://github.com/exercism/xswift/pull/68
Need to verify the others

**Comment by kytrinyx** [comment]
We might want to just close this. https://github.com/exercism/x-common/issues/279

**Comment by kytrinyx** [comment]
D'oh. Didn't mean to close it, just to comment :)
