### ISSUE TITLE
Detach Swift from apple platform

### ISSUE THREAD

**Issue by masters3d** [exercism/xswift#142]
Swift 2.2 is able to run on Ubuntu Linux. 
Microsoft just made their Ubuntu subsystem avalible to windows as Beta. 
https://insights.ubuntu.com/2016/04/14/howto-ubuntu-on-windows-2/

I believe the best time to transition would be when swift 3 becomes available (end of 2016)
We would need to update the instructions on how to run on Linux, Windows and macOS with our using xcode. 

Reference:
https://github.com/exercism/xswift/pull/141

**Comment by kotp** [comment]
Also I believe Xcode should be less of a 'must' and more of a 'can' in that document.

**Comment by masters3d** [comment]
Right now we are sort of dependent on Travis CI to add support for Swift Linux; once that happens we can move that way.

**Comment by masters3d** [comment]
In an effort to start the detachment of swift from apple we will drop the requirement of Xcode. We will start by removing the hello world xcode project. 
https://github.com/exercism/xswift/pull/219

In a subsequent update we will add instructions on how to use the package manager to generate an xcode version for the people who want it. 

this will require us to change the internals of each 

```
Package
└── Sources
    ├── Foo.swift
    └── Tests
        └── Test.swift
```

from there we can generate an xcode project by running

``swift package generate-xcodeproj``

**Comment by masters3d** [comment]
Working Sample:
https://github.com/masters3d/SwiftPackageManagerSamples/tree/master/Swift-PackageAccumulate
