### ISSUE TITLE
Initial Setup of Swift projects unclear

### ISSUE THREAD

**Issue by bobdel** [exercism/xswift#156]
There are several hurdles with beginning the Swift track would benefit from some attention. I am very new to exercism and somewhat new to programming, and I respect how much work it is to create these assets. These observations are offered as constructive criticism, and I do not mean to disparage the work already performed.

1. The "Running the Tests" instructions are based on the bob exercise, rather than the hello-world exercise.

2. The source files retrieved by the fetch operation for the hello-world exercise are not helpful as they do not match other exercises. For example, most exercises fetch two source documents, tests and a readme. Hello World contains an Xcode project and directory. And worse, the fetched Xcode project does not build as a standalone project.

_These two issues created a lot of false inferences on my part as I tried to get up to speed_. I ultimately worked out how exercism worked with Swift by finding the backing GitHub repositories for bob and hello-world, and comparing them to the instructions.

Recommendations

The "Running the Tests" instructions for Swift are strictly correct, although I still found them confusing until I figured out the basic workflow. (Again hello-world sent me off in the wrong direction initially.)

A few specific notes that might help make the running test instructions mode complete. 

a. Note that its better to use iOS Single View application even if you're ultimately going to work on OS X apps. 

b. I think asking newer developers to create a class file outside Xcode's normal default is a tall order, and it would be better to leave it in place. Then demonstrate how to submit it by dragging and dropping the class file from Xcode into the terminal window.

c. describe briefly difference between unit tests and compiling the project

d. add several additional images.

Expanding on the Running the Tests instructions to explain both how to create a new project and how to upload the final submission is something I would like to contribute to, but I'm not sure how. I love the whole exercism concept and would love to contribute back to it.

**Comment by masters3d** [comment]
I agree that Xcode brings in level of complexity that is not really needed. I am curious what you mean by "And worse, the fetched Xcode project does not build as a standalone project."

#142 we are planning on dropping the requirement on Xcode since you really do not need it to submit problems. The swift or objective c track are not really for learning Xcode or iOS.

**Comment by bobdel** [comment]
I can explain my initial confusion with Xcode now; I was unable to when I was first setting up exercism.

The hello-world project that is offered now as an example confused me because it only contains a test target, not a basic single view application. That, to my eyes, looked "broken." Especially since as soon as its opened, there is a red cannot compile error. I didn't realize that this was normal for unit tests, so I sent myself down a dead end road trying to understand why there was no AppDelegate, storyboard, etc.

I've built a dozen "beginner" apps in iOS. I have a basic understanding of targets and toolchains. But I do have expectations of how Xcode sets up projects. Incomplete expectations, no doubt. The test-only target left me unable to sort out what was wrong. Once I got unit tests working, I can see tests are built separate from an iOS app.

Again, this is rooted in my limitations. I'm trying to provide a window of what it looks like to a newcomer, not complain about things not working the way I want.

Now I realize that it is possible to create a test target project without an iOS app. If the readme explained a bit more about how the unit tests worked, that would have helped.

**Comment by masters3d** [comment]
ah, I see. I know the feeling. 

This is the doc that talks about the [tests](https://github.com/exercism/xswift/commits/master/docs/TESTS.md) You are welcome to submit changes to it on a github pull request. 

I found this that may be helpful but it is in objectiveC
https://developer.apple.com/library/tvos/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/02-quick_start.html#//apple_ref/doc/uid/TP40014132-CH2-SW1

Again at some point we are looking at moving away from xcode but I am not sure if that is going to make easier or more difficult.

**Comment by bobdel** [comment]
Thank you. This is all very helpful.
