### ISSUE TITLE
Newest exercises not appearing on website

### ISSUE THREAD

**Issue by robtimp** [exercism/xswift#165]
The latest Swift exercises (all-your-base and bracket-push) are still not present on exercism.io, even though an Objective-C exercise merged afterward is.

**Comment by robtimp** [comment]
@masters3d Any idea why this would happen? We haven't deprecated exercises before, so maybe it's a bug related to that?

**Comment by masters3d** [comment]
They are on a separate branch so they are not active. Only master gets pushed to the site I believe.

**Comment by masters3d** [comment]
You are welcome to push a swift 2 version to master if you'd like. xcode usually goes Gold Master around the first week of September.

**Comment by robtimp** [comment]
Oops, can't believe I forgot we weren't working on the Master branch.
