### ISSUE TITLE
AccumulateTest.swift fails to build in Xcode 8-Beta-6

### ISSUE THREAD

**Issue by codesman** [exercism/xswift#179]
Using Xcode 8-Beta-6, building the tests fail to build in `testAccumulateRecursively()` because `Cannot invoke 'XCTAssertEqual' with an argument list of type '([Array<String>], [[String]])'`.

I have tested many of the submitted answers as well as the example in the xswift repo and they are all failing in the same way.

There are a couple changes I needed to make to even get to this point.

First thing is that the extension(or function) needs to be declared public now or the build will fail.

The next thing is to add the `_` before the parameter name so it is not required in the call.

It appears that there needs to be another extension to make `[Array<String>]` Equatable?  I tried, but  failed to wrap my head around it.  How do we test equality on this now?

**Comment by masters3d** [comment]
We only support swift 2.2 at the moment. We have a `swift3` branch that we will merge once xcode 8 goes out of beta

**Comment by masters3d** [comment]
this is the reference bug: https://bugs.swift.org/browse/SR-2284

we have a work around the swift3 branch.

**Comment by codesman** [comment]
@masters3d ,

10-4.  I'll focus elsewhere until Xcode 8 is released.

FWIW, I was using the tests from the `swift3` branch.

**Comment by masters3d** [comment]
Oh okay. The tests are passing on the CI and locally with Xcode 8 b6
https://github.com/exercism/xswift/blob/swift3/exercises/accumulate/AccumulateTest.swift#L18-L20

PR's welcome :)

**Comment by masters3d** [comment]
We just pushed xcode 8 GM. Let me know if you have any issues. Closing for now.
