### ISSUE TITLE
Running from CLI?

### ISSUE THREAD

**Issue by johnpaulashenfelter** [exercism/xswift#2]
So how do you run these from the CLI?

**Comment by montlebalm** [comment]
Any progress on this @ahalls? I've been looking into running XCTests from the CLI, but I haven't made much progress.

**Comment by hankturowski** [comment]
Swift 2.0 was just announced at WWDC and Xcode 7 around the corner. We should probably put this on hold until they go gold.

**Comment by masters3d** [comment]
Im going to close this for now. We can revisit this when swift is stable in Linux.

**Comment by masters3d** [comment]
In swift 2.2 we now have the option to use the pure swift implementation of swift.  https://github.com/apple/swift-corelibs-xctest

Some limitations: https://github.com/apple/swift-corelibs-xctest#additional-considerations-for-swift-on-linux

We need to manual add all the test to 
```    var allTests : [(String, () -> Void)] {}```

We can handle this with a script 
https://gist.github.com/briancroom/e2c22f162f8ba5211e31

Then all we would need to do is to call this with all the Test classes. 

```XCTMain([BobTest(), Problem3Test(), ETCTest()])``

Live example with 2.2:

http://swiftlang.ng.bluemix.net/#/repl/b0d680996ae5506a06be941e7b1e642665ee35e51b0c216cb6d6f13957e18e41

**Comment by masters3d** [comment]
we now support linux. There is updated documentation to run from the command line.
