### ISSUE TITLE
More help with Testing with Xcode

### ISSUE THREAD

**Issue by celiagomezdev** [exercism/xswift#202]
Hi, I'm starting to code and the Apple developers documentation for Testing in Xcode is quite complex right now... Maybe you could add -some day- a simple guide (for complete dummies like me) about how to work with Xcode for testing, which are the steps and maybe also the basic syntax in an exercism exercise (bob for example)? Thanks.

**Comment by masters3d** [comment]
Thanks for writing in. Have you tried the hello world exercise?

**Comment by celiagomezdev** [comment]
Yes, I did! But I just practised in a playground file and then, when I saw that worked, I copied it in the hello-world.swift file and pushed it...

**Comment by masters3d** [comment]
Ah okay.  Have you seen this one too?

https://github.com/exercism/xswift/blob/master/docs/TESTS.md

I'm trying to figure out how to make it better or give it better exposure if you have seen it.

**Comment by celiagomezdev** [comment]
@masters3d Yes, I've followed all the steps, and besides 2 points that were a bit confusing (if you want I can tell you them as well later) everything went fine. The problem is that after that, I get stuck before the point: _"Now use CMD-U to run the tests, and happy coding!"_ (well also I don't know how to do that :/) Maybe it could be a guide for super newies about that? Between the previous point and this one, there is for me a big empty frustrating hole. In my case for example, in the LeapTest.swift, I don't know where it comes from the class LeapTest: XCTestCase, what means and what should I do with every function inside it, what means XCTAssertTrue(year.isLeapYear)... After 2 days researching and trying things I can figure out a bit how it works... I showed this guide to my developer friend: https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/02-quick_start.html#//apple_ref/doc/uid/TP40014132-CH2-SW1 and told me that this is thought for an experienced developer. Maybe would be interesting to add 2 or 3 more points explaining the unit tests syntax and steps inside Xcode...

**Comment by celiagomezdev** [comment]
But anyway, maybe I just can work with a playground file, and just push the final file once I know that the problem works, without using the XCT environment. I think I will study Unit Testing further in the course I'm doing.

**Comment by masters3d** [comment]
here is something you could use to only use the playground 
https://github.com/WhiskerzAB/PlaygroundTDD
I am afraid that could be a little more involved though.

**Comment by celiagomezdev** [comment]
@masters3d Hmmm the problem is just that I'm not used to any kind of TDD... My mentors told me that this will come later (now I should focus in learning to understand classes, functions, optionals...) but I though exercism was also thought for people that is starting to learn :/ I should give up now with excercism then and come back in the future?

**Comment by celiagomezdev** [comment]
For example, I uploaded here the exercise just to show you https://github.com/celiagomezdev/Leap
Now is giving the error 'Cannot load underlying module for XCTest' so I cannot test :/
Also, I don't know what exactly means the XCTAssertTrue(year.isLeapYear) line... I imagine it means that this test should return true, but what means and how the program read what is inside ()? Also, in the 'Hello World' excercise, is very complex to understand every part of: XCTAssertEqual(HelloWorld.hello("Alice"), expected, "When given 'Alice' we should greet Alice!").

(Thanks a lot for helping me)

**Comment by masters3d** [comment]
Use the `hello world` sample project as a guide. If you replace the files inside the hello world with the ones in leap, it should work. 

http://stackoverflow.com/questions/29965397/cannot-load-underlying-module-for-xctest

**Comment by celiagomezdev** [comment]
@masters3d I've managed to solve the problem at the end! And now I understand a bit how the XCTests work. But I still thinking it would help a little guide of the XCT workflow and syntax for very very newies. Thanks for your help!

**Comment by masters3d** [comment]
sounds good. let me know if you find a good tutorial and we will link it.

**Comment by celiagomezdev** [comment]
I didn't find... they were too long or too complex for non-experienced developers. Is that because I thought it would be good to add only two or three points more in this guide: https://github.com/exercism/xswift/blob/master/docs/TESTS.md 

between this point: 

> - Select Bob.swift and in the File Inspector make sure that both bob-swift and bob-swiftTests are checked in the Target Membership area.

and this one:

> - Now use CMD-U to run the tests, and happy coding!

Like for example (but more accurate explained): 

> - Write the code you consider in your working file (Bob.swift) in order to make the tests in LeapTest.swift work (now they will show you some errors, but writing the right code in your working file should make them disappear)._ 
> - Once you think that you are done, you just need to go to the Test Navigator (show image) and click the play button next to the tests. If they are correct, they will show a green mark, if not, they will show a red mark and highlight the non-passed tests. Modify your code in your working file until all the tests succeed.
> - Some syntax: XCTestCase class is the class that contains the tests, and every function is every test. Ignore all this in your working file Bob.swift, there you just need to write the code that will make every of those functions (tests) succeed... XCTAssert lines are the expected results, and there are different types that mean... Equal: ... True/False... For example, in the BobTest.swift file, the line XCTAssertEqual(expected, result) means that...

And then just the line:

> - Now use CMD-U (or directly in Xcode) to run the tests, and happy coding!

Maybe looks too obvious, but it would help a lot for the people who never had contact with programming or TDD before.

**Comment by masters3d** [comment]
Those look good to me. Do you want to submit a pull request with those changes?

**Comment by celiagomezdev** [comment]
Ok, done! Looking forward to your comments.

**Comment by masters3d** [comment]
Nice work. Thanks!
