### ISSUE TITLE
Cannot submit test file 

### ISSUE THREAD

**Issue by thebasharjobs** [exercism/xswift#208]
Hi there, reposting after redirection here from another forum, so my apologies if this appears to be a duplicate to anyone. 

At any rate, I can't submit a test file after completion and get the submission message:

"The message I continue to get is "You're trying to submit a test file. If this is really what you want, please pass the --test flag to exercism submit."

Any help would be appreciated. 

Thanks so much

**Comment by masters3d** [comment]
Hi! Thanks for reaching out. 

Are you trying to upload a solution and the test file using the command line?

**Comment by thebasharjobs** [comment]
Figured out the issue. The two files weren't contained in the same directory. 

*slaps forehead*

**Comment by masters3d** [comment]
oh okay. sorry if it was not clear. let me know if you need anything else. if not feel free to close this issue.
