### ISSUE TITLE
Images for a future update to the tests.md doc. No action required.

### ISSUE THREAD

**Issue by bobdel** [exercism/xswift#213]
![001-splash](https://cloud.githubusercontent.com/assets/5385825/20957611/c756745a-bc05-11e6-8631-e9e738ad464b.png)
![002-templatechooser](https://cloud.githubusercontent.com/assets/5385825/20957613/c770da16-bc05-11e6-82e1-7da6c2ca6de0.png)
![003-nameproject](https://cloud.githubusercontent.com/assets/5385825/20957616/c7793828-bc05-11e6-8c73-bb02a71322b2.png)
![004-saveproject](https://cloud.githubusercontent.com/assets/5385825/20957617/c77d5976-bc05-11e6-837d-1dacfe5e17c8.png)
![005-folderlayout](https://cloud.githubusercontent.com/assets/5385825/20957615/c77698d4-bc05-11e6-8117-7a7ec2fc035f.png)
![006-newprojectinitial](https://cloud.githubusercontent.com/assets/5385825/20957614/c77514f0-bc05-11e6-8514-4eec07736127.png)
![007-newprojectmidway](https://cloud.githubusercontent.com/assets/5385825/20957612/c769df04-bc05-11e6-9719-18b5aece0f2d.png)
![008-testsimportexample](https://cloud.githubusercontent.com/assets/5385825/20957618/c7800d4c-bc05-11e6-937f-de2f3743c1b6.png)
![009-finallayoutexample](https://cloud.githubusercontent.com/assets/5385825/20957619/c7832748-bc05-11e6-9626-2f8a01fdcf22.png)

**Comment by bobdel** [comment]
Sorry for the hack. I'm a newbie and this is my first try at this.

**Comment by masters3d** [comment]
Those are some good images! You don't have to actually create an issue to upload the images. Once the link has been created you can just copy it before you hit save on the issue :) Let me know if you have questions. There are probably better ways to do this.

**Comment by bobdel** [comment]
Thanks!

I tried to upload the images to the img folder like you suggests, but didn't find the right incantation to make it work. Agreed this was a messy hack and I need to do better next time.

How do the changes propagate onto the website? I see where the change is merged into the project, but the website still shows the pre-edited page.

Again, thanks for the hand holding. Github is very new territory for me.

**Comment by masters3d** [comment]
Oh I see. The images embedded in this issue do not live on this repo but are just stored in GitHub cloud general storage. If you look at the generated code by clicking edit, you will see the URLs for each image. This URLs are not part of the repo. 

Look up github markdown on google to see how to create image links in markdown documents.

**Comment by masters3d** [comment]
The changes propagate to the website I a couple of days whenever the maintainer of the websites pushes the changes to the actual webserver. We do not serve the website from github.

**Comment by kytrinyx** [comment]
I wrote some documentation about this. See https://github.com/exercism/xswift/issues/226
