### ISSUE TITLE
Front-end Website for Swift Missing Images

### ISSUE THREAD

**Issue by bobdel** [exercism/xswift#223]
I don't have the exercism-native terminology to explain this succinctly.

I contributed a new tutorial to the documentation for xswift, specifically TESTS.md.

Everything was fine when the page was merged into the xswift repo.

However when the page was moved to the server that hosts the exercism.io website, the links to the images broke. Since I don't know how the website part of exercism is managed, I never knew how to insure the links would migrate in the first place, other than to make sure it worked on the xswift repo. 

I'm not sure whose attention to bring this to, hence this message here.

At the moment, the new user onboarding path for the swift track is pretty much broken.

Can someone help me unravel this?

**Comment by masters3d** [comment]
You are the first to add images to the repo so this is the first time I see this. 

take a look at fsharp. 
https://github.com/exercism/xfsharp/edit/master/docs/TESTS.md
I guess there is a direct way to access the images once they have been deployed.

**Comment by masters3d** [comment]
Sorry I don't know what is going on. I cross posted this here.
https://github.com/exercism/exercism.io/issues/3312

**Comment by masters3d** [comment]
Here is the answer. 

https://github.com/exercism/xswift/pull/212#issuecomment-267659027

**Comment by masters3d** [comment]
https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md

**Comment by Insti** [comment]
The TESTS.md file needs to have its image paths updated.

`![001-splash](/img/page_assets/001-splash.png)`

Needs to be 

`![001-splash](/docs/img/page_assets/001-splash.png)`

And the `/img` directory needs to be moved from the xswift root into `docs/`

**Comment by bobdel** [comment]
Yes, I know. I'll take care of it shortly.
