### ISSUE TITLE
Swift Package manager

### ISSUE THREAD

**Issue by harquail** [exercism/xswift#233]
Using [Swift PM](https://github.com/apple/swift-package-manager/tree/master/Documentation) for Swift would simplify the workflow for development (no need to create an Xcode project).  Running tests is also simple: https://github.com/apple/swift-evolution/blob/master/proposals/0019-package-manager-testing.md.

More info here: https://github.com/apple/swift-package-manager/blob/master/Documentation/Reference.md#test-suite-layouts

**Comment by masters3d** [comment]
I agree. 
https://github.com/exercism/xswift/issues/142#issuecomment-266601381

PRs are welcomed.  ;)

**Comment by lyuha** [comment]
@masters3d Must PRs include about all exercises with docs? Or split to PR including update one exercise?

**Comment by masters3d** [comment]
You could make this one PR for all.  Docs get served separately. See sample in comment linked above.

**Comment by masters3d** [comment]
https://github.com/masters3d/SwiftPackageManagerSamples/tree/master/Swift-PackageAccumulate

**Comment by lyuha** [comment]
Ok. I update all exercises.

**Comment by harquail** [comment]
thanks to you both for taking this on 😸

**Comment by masters3d** [comment]
We need to update documentation before we can push into master.

**Comment by harquail** [comment]
I can make a PR to update the documentation, unless @lyuha wants that task?

**Comment by lyuha** [comment]
Good. I don't wants.

**Comment by masters3d** [comment]
Closing this now. We just need to make all tests pass on Linux before merging into master

**Comment by dgdosen** [comment]
Just started going through the swift exercises... and was going to suggest command line projects... but this is a much better idea.   Thanks for taking on this task!
