### ISSUE TITLE
Swift languages page: Instructions for running tests are outdated

### ISSUE THREAD

**Issue by jkrmr** [exercism/xswift#252]
At http://exercism.io/languages/swift/tests:

> For experienced users:
> 1. `swift test` runs tests
> 2. `swift package generate-xcodeproj` creates an Xcode project
> To run the tests from the command line, first cd to the exercise directory (for example, ~/exercism/swift/exercises/hello-world/), then execute swift test. This will compile the files in the Sources directory and execute the tests in the Tests directory. Alternatively, open the Xcode project and press Command-U.

**Comment by masters3d** [comment]
Let us know how we can improve it.
