### ISSUE TITLE
Instructions for Bob don't match tests

### ISSUE THREAD

**Issue by stevenhuey** [exercism/xswift#255]
There are two separate issues:

1. The [directions](https://github.com/exercism/x-common/blob/master/exercises/bob/description.md) show use "Whoa" for yelling and the tests expect "Woah".
2. The [directions](https://github.com/exercism/x-common/blob/master/exercises/bob/description.md) show "Fine. Be that way!" when nothing is said, and the tests expect "Fine, be that way."

**Comment by masters3d** [comment]
PRs are welcome. :) Thanks for letting us know.
