### ISSUE TITLE
GradeShool Test may be inappropriate

### ISSUE THREAD

**Issue by drinkingcoder** [exercism/xswift#258]
"
A set stores distinct values of the same type in a collection with no defined ordering. You can use a set instead of an array when the order of items is not important, or when you need to ensure that an item only appears once.
"
- introduced by apple developer

[Doc Address](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html)

But I have to return [Int:Set] when property sortedRoster is used, which suggested Set can be sorted.

**Comment by masters3d** [comment]
Can you include the code you are referring to?

**Comment by drinkingcoder** [comment]
Problem is here:[Grade School](http://exercism.io/exercises/swift/grade-school/readme)
Test suite is here:[Test Suite](http://exercism.io/exercises/swift/grade-school/test-suite)
```
    func XCTAssertEqualCollection (_ collectionS: Set<String>?, _ collectionA: [String]? ) {
        XCTAssert(sameCollection(collectionS, collectionA))
    }
```
This code in test makes the type of name list in sortedRoster must be Set<String>.

**Comment by masters3d** [comment]
You are correct we accidentally removed this from the test case. 

```swift
func XCTAssertEqualCollection (_ collectionA1: [String]?, _ collectionA2: [String]? ) {
    XCTAssert(sameCollection(collectionA1, collectionA2))
} 
```

Do you want to submit a PR to add it back in?

**Comment by regnerjr** [comment]
Could we make these test more generic? and have have them test things conforming to `Sequence` or `Collection` this way the user could write code targeting an Array or Set and have it pass one test. 

```
func XCTAssertEqualCollection (_ collectionA1: Sequence<String>?, _ collectionA2: Sequence<String?? ) {
  XCTAssert(sameCollection(collectionA1, collectionA2)) //sameCollectionWould have to be changed too
} 
```

**Comment by masters3d** [comment]
Sure. Right now its generic over `Collection` but its more of a hack really. I could not get the generic sameCollection to working without the another function overlay for `XCTAssert`. That is why there was suppose to be two versions of `XCTAssertEqualCollection`. PR's welcome :) Maybe something has change in swift 3. 

```swift
    // Workaround unit test limitation on Optional Arrays/Sets
    private func sameCollection<C: Collection>(_ result: C?, _ expected: [String]?) -> Bool where C.Iterator.Element == String {
        guard let result = result, let expected = expected, similar(result, expected) else { return false }
        for (index, student) in result.enumerated() {
            guard index < expected.count && expected.contains(student) else { return false }
        }
        return true
    }
    private func similar<C: Collection>(_ result: C, _ expected: [String]) -> Bool {
        return result.count.toIntMax() == IntMax(expected.count)
    }

    func XCTAssertEqualCollection (_ collectionS: Set<String>?, _ collectionA: [String]? ) {
        XCTAssert(sameCollection(collectionS, collectionA))
    }

// This was accidentally removed in another commit.  
    func XCTAssertEqualCollection (_ collectionA1: [String]?, _ collectionA2: [String]? ) {
        XCTAssert(sameCollection(collectionA1, collectionA2))
} 
```
