### ISSUE TITLE
GradeSchool sorted school test

### ISSUE THREAD

**Issue by hobbitjoe** [exercism/xswift#266]
When running the tests for GradeSchool I noticed that I had passed the test for checking the sortedRoster despite not actually doing any sorting.  Running my code through a repl I was able to see that the dictionary and contained arrays were not sorted.  Looking though the tests it looks like they may be incorrect.

Line 91:
`XCTAssertEqual(Array(result.keys).sorted(by: >), Array(expected.keys).sorted(by: >))`
The test is sorting the keys and then checking to see if they are equal.

Helper functions starting at line 6:
```// Workaround unit test liminitaiton on Optional Arrays/Sets
    private func sameCollection<C: Collection>(_ result: C?, _ expected: [String]?) -> Bool where C.Iterator.Element == String {
        guard let result = result, let expected = expected, similar(result, expected) else { return false }
        for (index, student) in result.enumerated() {
            guard index < expected.count && expected.contains(student) else { return false }
        }
        return true
    }
    private func similar<C: Collection>(_ result: C, _ expected: [String]) -> Bool {
        return result.count.toIntMax() == IntMax(expected.count)
    }

    func XCTAssertEqualCollection<C:Collection> (_ collectionS: C?, _ collectionA: [String]? ) where C.Iterator.Element == String {
        XCTAssert(sameCollection(collectionS, collectionA))
    }
```

These functions seem to just check to see if the number of items is correct and then if the student is contained within the expected list, not the order that the students are in.

**Comment by masters3d** [comment]
Sets and dictionaries are non sorted data types. 
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/CollectionTypes.html#//apple_ref/doc/uid/TP40014097-CH8-ID113

Keys can not be sorted, only arrays. Is this failing to check an arrays order?

**Comment by hobbitjoe** [comment]
That makes sense that dictionaries are non sorted data types, but for the array order this line seems to only be looking to see if its contained:
```guard index < expected.count && expected.contains(student) else { return false }```

**Comment by masters3d** [comment]
Yeah. This was added to be able to support `Set` data structure. I don't think is worth doing; we should just stick to `Array`. 
PR are welcome to remove this. 
Related: https://github.com/exercism/xswift/issues/259
