### ISSUE TITLE
swift package generate-xcodeproj generates error rootManifestNotFound

### ISSUE THREAD

**Issue by FakeHeal** [exercism/xswift#274]
So, I'm not an experience developer in Swift and I followed the guide precisely which lead me to nowhere.

>In the Terminal cd to the directory for an exercise (for example, ~/exercism/swift/exercises/hello-world/), then execute **swift package generate-xcodeproj**. This creates an Xcode project in the current directory with the same name as the package. (The generated project is ideal for unit tests. It does not include the overhead of launching the iOS simulator or a target application.) 

When I was executing **swift package generate-xcodeproj** I was getting:

> error: rootManifestFileNotFound

I read some articles/SO answers on the internet and found out that if I do:

> swift package init

and **then**:
> swift package generate-xcodeproj

No error was produced. So, is the guide outdated or I have missed something **very important** along the way.

**Comment by FakeHeal** [comment]
I got it, obviously missed the part with the 'fetch'-ing...

**Comment by masters3d** [comment]
PR for documentation updates are welcome. We want to be new user friendly.

**Comment by achinwo** [comment]
Updating docs...

**Comment by masters3d** [comment]
I am not sure what you asking?
