### ISSUE TITLE
Grade School should return a sorted Array with tuples instead of a dictionary

### ISSUE THREAD

**Issue by aarti** [exercism/xswift#51]
For the test `func testSortSchool() ` we want to return an object that is sorted by keys and values of the dictionary. It seems like the test is working too hard and may not even be right, since the keys in a [Swift Dictionary](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_Dictionary_Structure/index.html#//apple_ref/swift/struct/s:VSs10Dictionary) are not ordered.
Instead of 
       ` let expected = [
            3 : ["Kyle"],
            4 : [ "Christopher", "Jennifer" ],
            6 : [ "Kareem"]
        ]`       
We should return
`let expected = [ (3,["Kyle"]), (4,["Christopher", "Jennifer"] ),
    (6, ["Kareem"])]`

Also `tuples` are the swift way to return groups of multiple values.
I am still new to swift :) but I was at WWDC and showed my code to some devs at the swift lab. This was their suggestion.

**Comment by nickkjordan** [comment]
Seems reasonable.  There are certainly a lack of Tuples in the current Swift exercises

**Comment by hankturowski** [comment]
No objection from me. Go for it!

**Comment by aarti** [comment]
OK.

**Comment by masters3d** [comment]
I love tuples but I think current the implementation using the swift's associative container seems more appropriate. https://en.wikipedia.org/wiki/Associative_array

If a  [(key,value)] is required to be sorted, you could start by extending the Dictionary Type followed by in place sort or similar.
```swift
extension Dictionary{

    func toKeyValuePairArray() -> Array<(Key, Value)>{
        return Array(zip(self.keys, self.values))       
}
```
Probably the most suited container for this would be a NSOrderedSet
https://developer.apple.com/library/prerelease/ios/documentation/Foundation/Reference/NSOrderedSet_Class/index.html
