### ISSUE TITLE
Confused on method vs. variable

### ISSUE THREAD

**Issue by indiesquidge** [exercism/xswift#53]
So my code looks like this
```swift
func isLeapYear() -> Bool { ... }
```
Which Xcode complains about with the following errors when I run the tests
```swift
Function produces expected type 'Bool'; did you mean to call it with '()'?
```
and for the `!` tests
```swift
cannot invoke 'XCTAssertTrue' with an argument list of type '(Bool)'
```

However, when I change the tests from
```swift
XCTAssertTrue(!year.isLeapYear)
```
to
```swift
XCTAssertTrue(!year.isLeapYear())
```
Everything seems to work fine and the tests pass (because I have logic written for them that is excluded from this issue note).

I'm just curious as to what is going on here. I looked at the example answer you guys have in here, and instead of declaring `isLeapYear` to be a function, you invoke it as a local variable which passes the tests without having to add the parentheses.
```swift
var isLeapYear: Bool { ... }
```
I know that parentheses mean that you are calling some function on an object, but what are the major differences with this kind of implementation? When is it best to apply one over the other? Was the way I was constructing it as a function incorrect? I'm brand new to Swift (and programming in general, really), so some of these one-off things always take my head for a spin. If anyone would be able to clear it up I would be very appreciative.

**Comment by masters3d** [comment]
//what are the major differences with this kind of implementation? 
The one with out () is using a computed variable. 

//When is it best to apply one over the other? 

Is your preferrence. Foundation seems like to use both ways. I tend to think that computed property is cleaner. 

//Was the way I was constructing it as a function incorrect?

no if you prefer use a function.

**Comment by indiesquidge** [comment]
Thank you for the reply :)
