### ISSUE TITLE
Decoupling Swift from Cocoa's Foundation

### ISSUE THREAD

**Issue by masters3d** [exercism/xswift#54]
Swift and the Swift standard library are going to be open sourced by the end of 2015. 
This got me thinking about the use of Foundation classes ( NSDate, NSMutableArray, NSString etc ) in the problems.

Should we make it a point to decouple the tests and examples to focus on "pure" swift implementations since Foundation is not going to be available for Linux? 
In xcode 7 beta 5 there were some changes to NString and String that dealt with paths. 
https://forums.developer.apple.com/thread/13688

This is an indication that swift types are becoming more "pure" maybe because of the open source release.

This would mean not importing foundation.
Edit: 9-9-15

Current list of problems that depend on Foundation.

- [x] /acronym/AcronymExample.swift                  // No Native Swift for NSExpression
- [x] /bob/BobExample.swift                                 // No Native Swift for NSExpression
- [ ] /gigasecond/GigasecondExample.swift        // No Native Swift for NSDate
- [ ] /meetup/MeetupExample.swift                      // No Native Swift for NSDate
- [x] /word-count/WordCountExample.swift          //NSStringCompareOptions
- [ ] /wordy/WordyExample.swift                          //NSStringCompareOptions

**Comment by nickkjordan** [comment]
Yeah, I'm in favor of this.  I don't remember many tests actually using Foundation, but I don't know about the examples.

**Comment by hankturowski** [comment]
This is a good idea. We should always prefer the native Swift types over the Objective-C counterparts.

But, I think we should hold off on this until at least the official release of Swift 2.0. We'll have a lot of work to do updating tests anyway. We should probably start a thread on Swift 2 migration. Some of the changes like `@testable` will make things easier for us if we handle them correctly. I'm thinking that we provide a starter project along with the first exercise (as suggested in another issue) and provide instructions on how to add new exercises to that project. Then we can control the package name and make the rest of the process smooth.

I'd also like to reorder the exercises. I ran through the first few with a new group the other day and man, doing Bob second was brutal. String process was tedious, and I think we'd be better off having some quicker exercises early.

**Comment by masters3d** [comment]
This brings up another question:
Is there a value on keeping swift 1.2 versions of the problems around?
I can see v3 v4 of swift starting to change a lot but many people could have limitation on what they are working on ( think python 2 vs 3 ) etc.

**Comment by hankturowski** [comment]
I think we should just ditch the 1.2 stuff when we migrate. Maintaining two sets of exercise will be a real pain, and adoption rates will probably be astronomical like they are with iOS. I think Xcode is an automatic update from the App Store.

**Comment by masters3d** [comment]
Sounds good.

**Comment by masters3d** [comment]
Swift really needs an NSDate native also Regular expression.
