### ISSUE TITLE
Swift 2 migration

### ISSUE THREAD

**Issue by masters3d** [exercism/xswift#55]
Wait for swift 2 to come out of beta.

Prefer the native Swift types over the Objective-C counterparts.
https://github.com/exercism/xswift/issues/54

Switch some test to throw errors instead of nil when it makes sense
http://ericasadun.com/2015/07/28/nil-vs-throws-swiftlang/

Make use of more Enums in tests ( Specially now that Enums with String payloads get automatically converted to strings)

Make use of Generic extensions.

How to test out Protocol usage in tests?

**Comment by hankturowski** [comment]
We should be careful with Enums in tests. Remember that we want to let the user solve the exercises in a variety of ways and not corner them into using our Enums. We can provide feedback on the site about using Enums, but I think that letting the user find their own way is useful.

What do you guys think?

**Comment by masters3d** [comment]
The new error handling seems to be geared towards enums so we can use them
there when it makes sense.  I do agree with not forcing enums for
everything but I don't like stringly type all things.

**Comment by hankturowski** [comment]
The new error handling mechanism is really cool! I love that you can throw anything you want, as long as it conforms to to the `ErrorType` protocol. You're right though that enums are the natural type to throw. And `guard` sure is nice too.

Maybe we should write some exercises that demonstrate some of the new Swift 2 features.

**Comment by masters3d** [comment]
I did the initial port to swift 2.0 GM. Im going to wait for xcode 7 to be released to do a PR.

**Comment by hankturowski** [comment]
Did you use the new `@testable`? If so, what module name did you use? I'd like to use it, but without knowing the module the user chose beforehand, I'm not sure we can.

Any ideas?

**Comment by masters3d** [comment]
I tried using `@testable` but it would require us to split the examples
into their own modules. It doesn't allow importing the test target as
"testable" when I tried it.

My test peiject was a command line based project and it was really fast to
execute the tests.

Do we want to have a master project with all the tests and problems in one
spot if so where will that go?
