### ISSUE TITLE
Swift Reorder of Problems

### ISSUE THREAD

**Issue by masters3d** [exercism/xswift#56]
Here is the current list of problems with the number of submissions per each problem. 
@hankturowski you are right about the Bob problem. 54% of people drop out of the track on the second problem!

Leap (126)
Bob (58)
Hamming (47)
Word Count (48)
Etl (35)
Anagram (34)
Nucleotide Count (30)
Phone Number (24)
Grade School (18)
Robot Name (22)
Perfect Numbers (16)
Allergies (12)
Accumulate (11)
Sum Of Multiples (9)
Twelve Days (9)
Space Age (10)
Gigasecond (8)
Meetup (5)
Triangle (5)
Scrabble Score (6)
Roman Numerals (5)
Binary (4)
Prime Factors (3)
Raindrops (4)
Strain (5)
Atbash Cipher (5)
Crypto Square (5)
Trinary (4)
Rna Transcription (4)
Sieve (4)
Octal (4)
Luhn (4)
Series (4)
Pig Latin (4)
Pythagorean Triplet (4)
Difference Of Squares (4)
Secret Handshake (4)
Clock (3)
Simple Linked List (2)

https://github.com/exercism/xswift/issues/54

**Comment by hankturowski** [comment]
Okay, so right off the bat, I say we arbitrarily move Bob to about the middle of the list to remove that block. Then let's start a careful study of the rest of the problems.

How about we each go through and identify the "easy" problems first and get those to the top. We can decide on the ordering for the rest once we have a gentler introduction.

**Comment by hankturowski** [comment]
Made the change and issued a pull request. I'll let you merge it so we get two sets of eyes. I know it's an easy one, but it's better this way I think.

**Comment by kytrinyx** [comment]
This is such a great initiative. I've been wanting to start doing some of this analysis across the various tracks.

If you find that there are some queries or whatever that would help make this easier, we could totally make a simple admin-only page with stats or something.

**Comment by masters3d** [comment]
superseded by #170
