### ISSUE TITLE
Label all problems with the compatible version of swift

### ISSUE THREAD

**Issue by masters3d** [exercism/xswift#61]
A simple comment like so
//  09-14-15 Swift 2.0

**Comment by hankturowski** [comment]
This will be a real pain to maintain. What's the long term purpose?

**Comment by kytrinyx** [comment]
Could we put a small text file in the root dir, like `.version` and write a script that would replace the line in all of the problems?

Is the _09-14-15_ a date? If so, can we use _2015-14-09_ so that Europeans don't get confused? When I see things like _02-06-15_ I never know if it's February 6th or June 2nd.

**Comment by masters3d** [comment]
This is something that should be part of the language as a @ directive but I don't believe there is a way to mark the swift version of a file yet. 
nshipster.com/swift-system-version-checking/

I don't think maintaining this will be a problem if we use a "master" Xcode project so that we could just do a global search and replace in the project when versions change again.

Where should we place such project in the repo directory?

I saw many submittiions of the current problems already using swift beta. The hope is that in the long run this will communicate to the user the version of swift that the file was tested on.

**Comment by kytrinyx** [comment]
I'm not sure what a master project looks like. Is it a directory? Could we put it at the root level and then put it under "ignored" in the config.json file?

**Comment by masters3d** [comment]
cool. I'll place it in a folder and update the configure file when I do the PR for the update to swift 2.0
as for the comment, I am just going to include this 
```// Apple Swift version 2.0```
This is the standard way the version gets reported in the Swift REPL
http://stackoverflow.com/questions/30790188/how-do-i-see-which-version-of-swift-im-using-in-xcode

**Comment by masters3d** [comment]
With swift 2.2 now we have the ability to check the version using #swift(). I deleted the version string from all the files that had it and added some pre-emptive swift 3.0 checks to the test files in case some people wanted to use the pre-released swift 3.0.
https://github.com/exercism/xswift/commit/ccaa687e3f22b793f8098646e8047de0728b1639
