### ISSUE TITLE
Travis Integration 

### ISSUE THREAD

**Issue by masters3d** [exercism/xswift#63]
@kytrinyx Do you know how (or know who) to edit the travis script so that the current script wont break?
https://github.com/exercism/xswift/blob/master/.travis.yml

I'd like to add xcode build to to run the tests on Xcode project. 
http://docs.travis-ci.com/user/languages/objective-c/#Default-Test-Script

https://github.com/exercism/xswift/issues/42

**Comment by masters3d** [comment]
This is what I am thinking would work.

```
language: objective-c
osx_image: xcode7
xcode_project: '/xcodeProject/xSwift.xcodeproj'
xcode_scheme: 'xSwift Tests'
```

**Comment by kytrinyx** [comment]
I've never tried, but if you do it in a branch and push it up, travis should try to run the build.

**Comment by masters3d** [comment]
Appears to be working on the TestingTravis branch. 
https://travis-ci.org/exercism/xswift/builds/80469278
What do you think? push it to master?

**Comment by masters3d** [comment]
merged. ;) I'm excited about this. i'm geeking out with the travis logs.

**Comment by kytrinyx** [comment]
w00t! This is so cool.
