### ISSUE TITLE
Allergies Problem - Swift Enum

### ISSUE THREAD

**Issue by AJEzk** [exercism/xswift#74]
I am not sure if this is the right platform to raise this question/issue, but I am working thru the Allergies problem and I just can't figure out why the tests don't require the use of a swift enum to store the different allergies? I am able to get the tests to pass using static properties for the Allergies struct, but this excersise would look much prettier with an enum.

**Comment by kytrinyx** [comment]
@AJEzk My guess is that it just kind of happened that way.

@marianaIAm What's Gen's GitHub? I feel like between the two of you, you might have an opinion on this.

**Comment by hankturowski** [comment]
This was a tricky one because the cleanest solution is either a struct that conforms to `OptionSetType` or, as you suggested, an `enum` with integer raw values. I haven't looked at Allergies in a while but I seem to remember it being tough to design an API that allowed for either solution.

In writing the tests, I tried to avoid requiring a certain approach. I'm fairly sure that's why this one didn't require enum. I haven't looked too deeply at this one since Swift 2, so if you can think of a way to allow for `OptionSetType` or `enum`, I'd love the pull request.

If you can't think of a way to allow either solution, submit a pull request anyway. We're short on enumerations and I think it would help to have a few more.

**Comment by hankturowski** [comment]
I've thought about this some more and I'm having a lot of trouble figuring out a really clean way to handle this problem with `enum`s that didn't require some tricky handling. You could store the list of allergies in a `Set<Allergies>` and use `.contains()` to check, but then how would we encapsulate that behavior without leaking the implementation? Maybe use a factory? Am I missing an obvious solution?

I'm starting to think that sticking with `OptionSetType` really is the best solution, but I also would like more Enums in the Swift problem set.

**Comment by masters3d** [comment]
https://gist.github.com/masters3d/5e91105d2ef994c4211e
This could allow struct or enum solutions.

**Comment by hankturowski** [comment]
Clever. I was hung up on instantiating an allergy set, but your static method sidesteps the issue nicely. I like it.

**Comment by AJEzk** [comment]
I was thinking something very similar to @masters3d.

The tests would look something like this: 

```swift

class AllergiesTest: XCTestCase {
    
    func testBob() {
        
        let patient = Patient(34)
        
        XCTAssertTrue(patient.hasAllergy(Allergies.Peanuts), "Bob is allergic to peanuts")
        XCTAssertTrue(patient.hasAllergy(Allergies.Chocolate), "Bob is allergic to chocolate")
        XCTAssertFalse(patient.hasAllergy(Allergies.Cats),  "Bob is not allergic to cats")
    }
    
    func testEggsNcats() {
        
        let patient = Patient(129)
        
        XCTAssertTrue(patient.hasAllergy(Allergies.Eggs))
        XCTAssertTrue(patient.hasAllergy(Allergies.Cats))
        XCTAssertFalse(patient.hasAllergy(Allergies.Chocolate))
        
    }
    
    func testNone() {
        let patient = Patient(0)
        
        XCTAssertFalse(patient.hasAllergy(Allergies.Pollen))
    }
    
    func testAll() {
        
        let allInt =  UInt(Array(0...7).reduce(0){ return ($0 | (1 << $1)) })
        let patient = Patient(allInt)
        
        XCTAssertTrue(patient.hasAllergy(Allergies.Eggs))
        XCTAssertTrue(patient.hasAllergy(Allergies.Peanuts))
        XCTAssertTrue(patient.hasAllergy(Allergies.Shellfish))
        XCTAssertTrue(patient.hasAllergy(Allergies.Strawberries))
        XCTAssertTrue(patient.hasAllergy(Allergies.Tomatoes))
        XCTAssertTrue(patient.hasAllergy(Allergies.Chocolate))
        XCTAssertTrue(patient.hasAllergy(Allergies.Pollen))
        XCTAssertTrue(patient.hasAllergy(Allergies.Cats))
        
    }
}
```

A sample solution would look like this:
```swift
enum Allergies: UInt {
        case Eggs = 1
        case Peanuts = 2
        case Shellfish = 4
        case Strawberries = 8
        case Tomatoes = 16
        case Chocolate = 32
        case Pollen = 64
        case Cats = 128
}

struct Patient {
    let score: UInt
    
    init(_ score: UInt) {
        self.score = UInt(score)
    }

    func hasAllergy(allergen: Allergies) -> Bool {
        return allergen.rawValue & score == allergen.rawValue ? true : false
    }
} 
```

**Comment by AJEzk** [comment]
I was thinking something very similar to @masters3d.

The tests would look something like this: 

```swift

class AllergiesTest: XCTestCase {
    
    func testBob() {
        
        let patient = Patient(34)
        
        XCTAssertTrue(patient.hasAllergy(Allergies.Peanuts), "Bob is allergic to peanuts")
        XCTAssertTrue(patient.hasAllergy(Allergies.Chocolate), "Bob is allergic to chocolate")
        XCTAssertFalse(patient.hasAllergy(Allergies.Cats),  "Bob is not allergic to cats")
    }
    
    func testEggsNcats() {
        
        let patient = Patient(129)
        
        XCTAssertTrue(patient.hasAllergy(Allergies.Eggs))
        XCTAssertTrue(patient.hasAllergy(Allergies.Cats))
        XCTAssertFalse(patient.hasAllergy(Allergies.Chocolate))
        
    }
    
    func testNone() {
        let patient = Patient(0)
        
        XCTAssertFalse(patient.hasAllergy(Allergies.Pollen))
    }
    
    func testAll() {
        
        let allInt =  UInt(Array(0...7).reduce(0){ return ($0 | (1 << $1)) })
        let patient = Patient(allInt)
        
        XCTAssertTrue(patient.hasAllergy(Allergies.Eggs))
        XCTAssertTrue(patient.hasAllergy(Allergies.Peanuts))
        XCTAssertTrue(patient.hasAllergy(Allergies.Shellfish))
        XCTAssertTrue(patient.hasAllergy(Allergies.Strawberries))
        XCTAssertTrue(patient.hasAllergy(Allergies.Tomatoes))
        XCTAssertTrue(patient.hasAllergy(Allergies.Chocolate))
        XCTAssertTrue(patient.hasAllergy(Allergies.Pollen))
        XCTAssertTrue(patient.hasAllergy(Allergies.Cats))
        
    }
}
```

A sample solution would look like this:
```swift
enum Allergies: UInt {
        case Eggs = 1
        case Peanuts = 2
        case Shellfish = 4
        case Strawberries = 8
        case Tomatoes = 16
        case Chocolate = 32
        case Pollen = 64
        case Cats = 128
}

struct Patient {
    let score: UInt
    
    init(_ score: UInt) {
        self.score = UInt(score)
    }

    func hasAllergy(allergen: Allergies) -> Bool {
        return allergen.rawValue & score == allergen.rawValue ? true : false
    }
} 
```

**Comment by masters3d** [comment]
Also you can drop the enum name from the test case
``hasAllergy( .Pollen)``
The compiler is able to tell which enum type it takes so it doesn't enforce the name to be included.

**Comment by masters3d** [comment]
Thanks @AJEzk for the PR!

**Comment by AJEzk** [comment]
Yes! My first open source contribution! :)

**Comment by masters3d** [comment]
Nice!

**Comment by hankturowski** [comment]
@AJEzk The first of many, I hope! Great work!
