### ISSUE TITLE
Resources for learning Swift

### ISSUE THREAD

**Issue by jtrudell** [exercism/xswift#89]
On the learning resources page (http://exercism.io/languages/swift#learning), Swifty App is a good start. I would also add Apple's free iBook, The Swift Programming Language, which is pretty accessible:  https://itunes.apple.com/us/book/the-swift-programming-language/id881256329?mt=11

**Comment by masters3d** [comment]
Do you mind doing a PR here?

https://github.com/exercism/xswift/blob/master/docs/RESOURCES.md

**Comment by masters3d** [comment]
Or maybe here. https://github.com/exercism/xswift/blob/master/docs/LEARNING.md

**Comment by jtrudell** [comment]
Will do.

**Comment by masters3d** [comment]
Thanks! https://github.com/exercism/xswift/pull/90
